'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {pathToFileURL,fileURLToPath}=require('node:url');
const root=path.resolve(__dirname,'..');
if(!process.versions.electron){
  const env={...process.env};delete env.ELECTRON_RUN_AS_NODE;
  const child=require('node:child_process').spawn(require('electron'),[__filename],{cwd:root,env,stdio:'inherit'});
  child.on('exit',code=>process.exitCode=code??1);
}else{
  const {app,BrowserWindow,ipcMain}=require('electron');
  const {sidebarState,updateSidebar}=require('../src/sidebar-state.cjs');
  const output=path.join(root,'.local',`sidebar-ui-${randomUUID()}`),entry=path.join(root,'renderer/index.html');
  app.setPath('userData',path.join(output,'profile'));app.disableHardwareAcceleration();
  app.commandLine.appendSwitch('force-device-scale-factor','1');app.commandLine.appendSwitch('force-prefers-reduced-motion');
  const ids=Array.from({length:32},()=>randomUUID()),scope='fixture-owner';
  let saved={projects:['/Users/preview/Projects/BeingDesktop','/Users/preview/Projects/HeartPortal']},win,createCalls=0,failMutation=false;
  const state={version:'sidebar-fixture',desktopId:randomUUID(),machine:{platform:'darwin',hostname:'Preview Mac',user:'Preview'},connection:{configured:true,status:'connected',beingName:'cz_being',displayUrl:'https://fixture.invalid/loom/'},workspace:{path:saved.projects[0],files:[]},portal:{status:'not_configured'},runtime:{configStatus:'unknown',sideBySide:{}},settings:{chatMode:'native',closeToTray:true},chatSessions:{activeId:ids[0],items:ids.map((id,i)=>({id,title:['重新设计桌面侧边栏','Portal 更新与一键接管','优化工具权限设置','整理项目文档'][i%4]+(i>3?` ${i}`:''),createdAt:Date.now()-i*3600000}))},chatSessionActivity:{},townApp:{access:{},identity:{},portalWorkspace:{path:'/preview'},portalInstall:{status:'idle'}}};
  for(let i=0;i<6;i++)saved=updateSidebar(saved,scope,state.workspace.path,{scope,type:'move',id:ids[i],project:saved.projects[i%2]},ids);
  saved=updateSidebar(saved,scope,state.workspace.path,{scope,type:'pin',id:ids[0]},ids);
  const snapshot=()=>({...state,sidebar:sidebarState(saved,scope,state.workspace.path)});
  const publish=()=>win.webContents.send('being:state',snapshot());
  const report={checks:[],errors:[],screenshots:[],calls:[],scope:'Actual renderer and preload; isolated fake sessions and native metadata reducer; no production service, messages, or files changed.'};
  const check=(name,passed)=>{report.checks.push({name,passed:!!passed});assert(passed,name);};
  const execute=script=>{assert.equal(win.webContents.getURL(),pathToFileURL(entry).href);return win.webContents.executeJavaScript(script);};
  const settle=()=>execute('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
  const until=async condition=>{for(let i=0;i<150;i++){if(await execute(`Boolean(${condition})`))return;await new Promise(r=>setTimeout(r,20));}throw new Error('Timed out: '+condition);};
  const click=async selector=>{await execute(`document.querySelector(${JSON.stringify(selector)}).click()`);await settle();};
  const menuClick=async label=>{await execute(`(()=>{const node=[...document.querySelectorAll('#sidebar-menu button')].find(node=>node.textContent===${JSON.stringify(label)});if(!node)throw Error('Missing menu item');node.click();})()`);await settle();};
  const key=async(key,modifiers={})=>{await execute(`document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:${JSON.stringify(key)},bubbles:true,cancelable:true,...${JSON.stringify(modifiers)}}))`);await settle();};
  const handle=(name,fn)=>ipcMain.handle('being:'+name,(_event,...args)=>{report.calls.push(name);return fn(...args);});
  const capture=async name=>{await settle();await new Promise(r=>setTimeout(r,80));const file=path.join(output,name+'.png');await fs.writeFile(file,(await win.webContents.capturePage()).toPNG());report.screenshots.push(file);};
  async function run(){
    await fs.mkdir(output,{recursive:true});await app.whenReady();
    handle('getState',snapshot);handle('refresh',snapshot);handle('getWindowState',()=>({platform:'darwin'}));
    handle('getTownCatalog',()=>require('../src/town.cjs').getTownCatalog());
    handle('getModelConfig',()=>({config:{model:'fixture',provider:'openai',baseUrl:'https://fixture.invalid',hasApiKey:false},models:[],providers:[],connectionId:1}));
    handle('getOrchestration',()=>({mode:{enabled:false,paths:{}},agents:[],workers:[]}));
    handle('getTownAppState',()=>state.townApp);handle('getFeatureTasks',()=>({tasks:[]}));
    handle('getDesktopTools',()=>({browser:{tabs:[],activeTabId:null},console:{jobs:[]},link:{status:'disconnected'},requests:[],workspace:state.workspace.path}));
    handle('getTerminalState',()=>({sessions:[],activeSessionId:null}));
    for(const name of ['setView','setBrowserView','markShellEditingTarget'])handle(name,()=>({}));
    handle('sidebarAction',action=>{if(failMutation)throw Error('Fixture write failed');saved=updateSidebar(saved,scope,state.workspace.path,action,state.chatSessions.items.map(item=>item.id));publish();return snapshot();});
    handle('renameChatSession',(id,title)=>{state.chatSessions.items.find(item=>item.id===id).title=title;publish();return true;});
    handle('changeChatSession',async(id,project)=>{createCalls++;await new Promise(r=>setTimeout(r,80));if(id===null){id=randomUUID();state.chatSessions.items.unshift({id,title:'新会话',createdAt:Date.now()});saved=updateSidebar(saved,scope,state.workspace.path,{scope,type:'move',id,project},[id]);}if(project)state.workspace.path=project;state.chatSessions.activeId=id;publish();return {ok:true};});
    handle('selectSavedProject',project=>{state.workspace.path=project;return snapshot();});
    handle('selectWorkspace',()=>snapshot());
    handle('desktopAction',()=>({browser:{tabs:[],activeTabId:null},console:{jobs:[]},link:{status:'disconnected'},requests:[],workspace:state.workspace.path}));
    handle('terminalAction',()=>({sessions:[],activeSessionId:null}));
    win=new BrowserWindow({show:false,frame:false,width:1280,height:850,useContentSize:true,webPreferences:{preload:path.join(root,'src/preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false,backgroundThrottling:false,offscreen:true}});
    win.webContents.on('console-message',event=>{if(event.level==='error')report.errors.push(event.message);});
    win.webContents.session.webRequest.onBeforeRequest((details,callback)=>callback({cancel:!details.url.startsWith('file:')||!fileURLToPath(details.url).startsWith(path.join(root,'renderer')+path.sep)}));
    await win.loadFile(entry);await until("document.getElementById('app-version').textContent==='sidebar-fixture'");await execute('document.fonts.ready');
    check('primary-entry-order',await execute("[...document.querySelectorAll('.primary-nav button')].map(node=>node.id).join(',')==='new-chat-session,sidebar-search,sidebar-fireside,sidebar-bonfire,sidebar-apps'"));
    check('tools-removed-from-sidebar',await execute("!document.querySelector('#sidebar #nav-browser,#sidebar #nav-console,#sidebar #nav-tasks,#sidebar-town-content,.sidebar-brand')"));
    check('projects-contain-their-tasks',await execute("document.querySelectorAll('.project-task-list .sidebar-task-row').length===5"));
    check('pinned-task-only-once',await execute(`document.querySelectorAll('[data-task-id="${ids[0]}"]').length===1&&document.querySelector('#sidebar-pinned [data-task-id="${ids[0]}"]')!==null`));
    check('only-current-task-selected',await execute("document.querySelectorAll('.sidebar .session-shortcut[aria-current=page]').length===1"));
    check('profile-pinned-bottom-single-scroll',await execute("getComputedStyle(document.getElementById('sidebar-scroll')).overflowY==='auto'&&getComputedStyle(document.getElementById('sidebar-session-content')).overflowY==='visible'&&document.getElementById('sidebar-profile').getBoundingClientRect().bottom<=innerHeight"));
    await capture('01-sidebar-dark-1280');
    await click('#sidebar-project-toggle');check('section-folds',await execute("document.getElementById('sidebar-project-content').hidden"));
    publish();await settle();check('fold-survives-state-update',await execute("document.getElementById('sidebar-project-content').hidden"));
    await win.reload();await until("document.getElementById('app-version').textContent==='sidebar-fixture'");check('fold-survives-reload',await execute("document.getElementById('sidebar-project-content').hidden"));await click('#sidebar-project-toggle');
    await click('#workspace-shortcut');check('project-click-expands-without-switching-page',await execute("document.querySelector('.project-task-list').hidden&&document.body.dataset.page==='chat'"));await click('#workspace-shortcut');
    await click(`[data-task-id="${ids[1]}"] .task-more`);await menuClick('置顶');await until(`document.querySelector('#sidebar-pinned [data-task-id="${ids[1]}"]')`);check('pin-saved-and-moved',sidebarState(saved,scope).tasks[ids[1]].pinned);
    await click(`[data-task-id="${ids[1]}"] .task-more`);await menuClick('重命名');await until("document.querySelector('.session-name-input')");await key('Escape');check('rename-cancel-restores-task',await execute(`!!document.querySelector('[data-task-id="${ids[1]}"] .session-title')&&!document.querySelector('.session-editing')`));
    await click(`[data-task-id="${ids[1]}"] .task-more`);await menuClick('重命名');await execute("document.querySelector('.session-name-input').value='新的会话名称'");await key('Enter');await until("!document.querySelector('.session-editing')");check('rename-persisted',state.chatSessions.items.find(item=>item.id===ids[1]).title==='新的会话名称');
    await click(`[data-task-id="${ids[1]}"] .task-more`);await menuClick('归档会话');await until(`!document.querySelector('[data-task-id="${ids[1]}"]')`);check('archive-keeps-underlying-session',state.chatSessions.items.some(item=>item.id===ids[1]));
    await click('#sidebar-task-options');await menuClick('查看已归档会话');await until("document.getElementById('sidebar-search-dialog').open");check('archive-search-finds-session',await execute("document.getElementById('sidebar-search-results').textContent.includes('新的会话名称')"));await capture('02-archive-search');await click('.sidebar-search-result');await until(`document.querySelector('[data-task-id="${ids[1]}"]')`);check('archive-recovery-restores-session',!sidebarState(saved,scope).tasks[ids[1]].archived);
    await click('#sidebar-search');await execute("document.getElementById('sidebar-search-input').value='完全不存在';document.getElementById('sidebar-search-input').dispatchEvent(new Event('input'))");check('search-has-empty-state',await execute("document.getElementById('sidebar-search-results').textContent.includes('没有找到')"));await execute("document.getElementById('sidebar-search-input').value='权限';document.getElementById('sidebar-search-input').dispatchEvent(new Event('input'))");await key('ArrowDown');check('search-keyboard-selects-next',await execute("document.querySelector('#sidebar-result-1').getAttribute('aria-selected')==='true'"));await key('Enter');await until("!document.getElementById('sidebar-search-dialog').open");
    await until("!document.getElementById('new-chat-session').disabled");const before=createCalls;await execute("document.getElementById('new-chat-session').click();document.getElementById('new-chat-session').click()");await until("!document.getElementById('new-chat-session').disabled");check('new-task-deduplicates-clicks',createCalls===before+1);check('new-task-is-standalone',sidebarState(saved,scope).tasks[state.chatSessions.activeId].project==='');
    await click('.project-new-task');await until("!document.querySelector('.project-new-task').disabled");check('project-new-task-binds-project',sidebarState(saved,scope).tasks[state.chatSessions.activeId].project===saved.projects[0]);
    failMutation=true;await click(`[data-task-id="${state.chatSessions.activeId}"] .task-more`);await menuClick('置顶');await until("document.getElementById('toast-region').textContent.includes('Fixture write failed')");check('failed-save-preserves-task',!sidebarState(saved,scope).tasks[state.chatSessions.activeId].pinned);failMutation=false;
    await click('#sidebar-profile');await menuClick('功能任务记录');check('feature-tasks-reachable',await execute("document.body.dataset.page==='tasks'"));check('no-task-selected-on-another-page',await execute("document.querySelectorAll('.sidebar .session-shortcut[aria-current=page]').length===0"));
    await click('#sidebar-apps');check('town-functions-reachable',await execute("document.body.dataset.page==='town'&&document.querySelectorAll('.town-feature').length===9"));
    await click('#sidebar-profile');await menuClick('设置');check('settings-reachable-from-profile',await execute("document.body.dataset.page==='settings'"));await execute("document.querySelector('.settings-back').click()");
    await click('#open-browser');check('toolbar-opens-browser',await execute("!document.getElementById('desktop-tools').hidden&&document.getElementById('open-browser').getAttribute('aria-pressed')==='true'"));await click('#sidebar-search');await click('#sidebar-search-close');check('search-preserves-tool-panel',await execute("!document.getElementById('desktop-tools').hidden"));await click('#open-browser');check('toolbar-toggles-browser-closed',await execute("document.getElementById('desktop-tools').hidden"));
    await click('#open-console');check('toolbar-opens-console',await execute("!document.getElementById('desktop-tools').hidden&&document.getElementById('open-console').getAttribute('aria-pressed')==='true'"));await click('#open-console');check('toolbar-toggles-console-closed',await execute("document.getElementById('desktop-tools').hidden"));
    await click('#toggle-sidebar');check('sidebar-collapses',await execute("document.body.classList.contains('sidebar-collapsed')"));await win.reload();await until("document.getElementById('app-version').textContent==='sidebar-fixture'");check('collapsed-sidebar-restored',await execute("document.body.classList.contains('sidebar-collapsed')"));await click('#toggle-sidebar');
    await execute("document.getElementById('sidebar-resizer').focus()");await key('ArrowRight');check('sidebar-width-can-be-adjusted',await execute("document.getElementById('sidebar').getBoundingClientRect().width===264"));
    await win.reload();await until("document.getElementById('app-version').textContent==='sidebar-fixture'");check('sidebar-width-is-restored',await execute("document.getElementById('sidebar').getBoundingClientRect().width===264"));
    for(const size of [[1000,700],[1440,940]]){win.setContentSize(...size);await settle();check(`fits-${size[0]}`,await execute("document.documentElement.scrollWidth===innerWidth&&document.getElementById('sidebar-profile').getBoundingClientRect().bottom<=innerHeight"));await capture(`03-sidebar-${size[0]}`);}
    await execute("for(const [key,value] of Object.entries(window.beingThemeColors.themeVariables(window.beingThemeColors.PRESETS.find(item=>item.id==='light').colors)))document.documentElement.style.setProperty(key,value)");
    await capture('04-sidebar-light');
    check('light-theme-keeps-sidebar-readable',await execute("getComputedStyle(document.getElementById('sidebar-profile')).color!=='rgb(236, 236, 236)'"));
    state.connection={...state.connection,status:'disconnected'};publish();await settle();check('disconnected-new-task-is-disabled',await execute("document.getElementById('new-chat-session').disabled"));
    check('no-script-errors',report.errors.length===0);
    report.passed=true;
  }
  run().catch(error=>{report.passed=false;report.error=error.stack;}).finally(async()=>{await fs.mkdir(output,{recursive:true});await fs.writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,error:report.error,errors:report.errors,report:path.join(output,'report.json')}));win?.destroy();app.exit(report.passed?0:1);});
}
